### ISSUE TITLE
Create a Logo

### ISSUE THREAD

**Issue by hparcells** [reverse-squared/material-clicker#2]
This is an upcoming game that we will be working on, and we will need a logo to implement when we start. When creating one, here are some of the things we should keep in mind:

- It should be kept very simple.
- They should be SVGs.
---
- We should have an icon which is a square, then a "banner" that includes the name of the game including the icon.
- **Color**: This is very important, try to use #2196f3 and #ffffff only.

For some inspiration, here are [the icons and banners](https://github.com/reverse-squared/old-material-clicker-2/issues/2#issuecomment-464211889) we used the previous iteration of this game.

![image](https://user-images.githubusercontent.com/40444294/66787217-d82d1a00-eeb0-11e9-8af5-6200d1dc6184.png)

**Comment by Erick2280** [comment]
Hi! I made a new logo following what you asked for.

![New logo proposal](https://user-images.githubusercontent.com/5215968/66794018-46d09e80-eed6-11e9-8dd7-c0ba25e28032.png)

![New icon proposal](https://user-images.githubusercontent.com/5215968/66794108-93b47500-eed6-11e9-9f82-446b951511aa.png)

I would like to suggest the adoption of a darker color (0a72c7), considering that the current color does not comply with the [WCAG 2.0 guidelines for contrast accessibility](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html).

![New logo proposal with a darker color](https://user-images.githubusercontent.com/5215968/66794079-7bdcf100-eed6-11e9-8b4f-d20bf34c76a9.png)

![New icon proposal with a darker color](https://user-images.githubusercontent.com/5215968/66794110-96af6580-eed6-11e9-99b8-751f8c8273ed.png)

**Comment by hparcells** [comment]
Looks great! I forgot to mention, if you want to throw the icons in a PR, just create a folder called `icons` in the root and we will handle them later.
